// <auto-generated />
using System;
using FTServer.Database.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FTServer.Database.MySql.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    partial class MySqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FTServer.Database.Core.Model.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ap")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("BagId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Dexterity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("DressId")
                        .HasColumnType("int");

                    b.Property<int>("DyeId")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<int>("GlassesId")
                        .HasColumnType("int");

                    b.Property<int>("GlovesId")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("HairId")
                        .HasColumnType("int");

                    b.Property<int>("HatId")
                        .HasColumnType("int");

                    b.Property<int>("MaximumInventoryCount")
                        .HasColumnType("int");

                    b.Property<bool>("NameChangeAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PantsId")
                        .HasColumnType("int");

                    b.Property<int>("RacketId")
                        .HasColumnType("int");

                    b.Property<int>("ShoesId")
                        .HasColumnType("int");

                    b.Property<int>("SocksId")
                        .HasColumnType("int");

                    b.Property<byte>("Stamina")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("StatusPoints")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Strength")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Willpower")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<byte>("Unknown0")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Unknown1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("X")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Y")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Furniture");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FamousPoints")
                        .HasColumnType("int");

                    b.Property<int>("HousingPoints")
                        .HasColumnType("int");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte>("UseType")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DisabledUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.LoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<bool>("Successful")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.RelayServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Heartbeat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Host")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<ushort>("Port")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RelayServers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RelayServer");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.GameServer", b =>
                {
                    b.HasBaseType("FTServer.Database.Core.Model.RelayServer");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("GameServer");
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Character", b =>
                {
                    b.HasOne("FTServer.Database.Core.Model.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Furniture", b =>
                {
                    b.HasOne("FTServer.Database.Core.Model.Home", "Home")
                        .WithMany("Furniture")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Home", b =>
                {
                    b.HasOne("FTServer.Database.Core.Model.Character", "Character")
                        .WithMany("Homes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Item", b =>
                {
                    b.HasOne("FTServer.Database.Core.Model.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.Login", b =>
                {
                    b.HasOne("FTServer.Database.Core.Model.Account", "Account")
                        .WithMany("Logins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FTServer.Database.Core.Model.LoginAttempt", b =>
                {
                    b.HasOne("FTServer.Database.Core.Model.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
